/* v11.6 God population controls */
let godAgentClan=0,godSpawnRole='worker',godSpawnCount=1,godAgentTapMode=null;
function godClan(){return clans[clamp(godAgentClan,0,Math.max(0,clans.length-1))]||clans[0]}
function godSpawnAt(c,role,count,x,y){if(!c)return;for(let i=0;i<count;i++){let r=role==='random'?pick(['worker','builder','guard','raider','medic','scout']):role;let a=spawnAgent(c.id,clamp(x+R(-30,30),8,WORLD.w-8),clamp(y+R(-30,30),8,WORLD.h-8),r);a.hunger=R(5,30);a.morale=R(72,96);if(r==='heavy'){a.role='heavy';a.weapon='maul';a.hp=130}if(r==='leader'){a.role='leader';a.weapon='spear';a.fame+=12;a.name='Chief '+a.name.replace(/^Chief /,'');c.leader=a;c.rulerDynasty=a.dynasty}}
function godSpawnHome(role,count){let c=godClan();if(!c)return;let p=c.capital||c.home;godSpawnAt(c,role,count,p.x,p.y);say(`⚡ The gods send ${count} ${role==='random'?'new souls':role+(count>1?'s':'')} to ${c.name}.`,count>=10)}
function godKillSelected(){if(selected&&selected.alive){let n=selected.name;selected.alive=false;say(`☠️ The gods strike down ${n}.`,true);selected=null}else say('☠️ Select a living agent on the map first.')}
function godPromoteSelected(){if(selected&&selected.alive){let c=clans[selected.c];selected.role='leader';selected.weapon='spear';selected.fame+=20;selected.hp=Math.max(selected.hp,115);selected.name=selected.name.startsWith('Chief ')?selected.name:'Chief '+selected.name;c.leader=selected;c.rulerDynasty=selected.dynasty;say(`👑 The gods crown ${selected.name} ruler of ${c.name}.`,true)}else say('👑 Select an agent first.')}
function godImmortalSelected(){if(selected&&selected.alive){selected.godImmortal=!selected.godImmortal;selected.age=Math.min(selected.age,35);selected.hp=Math.max(selected.hp,140);say(`✨ ${selected.name} is ${selected.godImmortal?'made immortal':'returned to mortality'}.`,true)}else say('✨ Select an agent first.')}
function godConvertSelected(){if(selected&&selected.alive){let c=godClan(),old=clans[selected.c];if(c&&old&&c.id!==old.id){selected.c=c.id;selected.memory.home=c.id;selected.goal={type:'move',x:c.home.x,y:c.home.y};selected.morale=90;say(`🔄 ${selected.name} defects from ${old.name} to ${c.name}.`,true)}}else say('🔄 Select an agent first.')}
function godWipeArmy(){let c=godClan();if(!c)return;let army=agents.filter(a=>a.alive&&a.c===c.id&&['guard','raider','heavy','scout'].includes(a.role));for(const a of army)a.alive=false;say(`💀 The fighting force of ${c.name} is wiped from history.`,true)}
function godMigration(){let c=godClan();if(!c)return;let p=c.capital||c.home;let count=Math.min(25,Math.max(8,Math.floor(agents.filter(a=>a.alive&&a.c===c.id).length*.3)));for(let i=0;i<count;i++){let a=spawnAgent(c.id,p.x+R(-70,70),p.y+R(-70,70),'random');a.role=pick(['worker','builder','medic','scout']);a.goal={type:'move',x:clamp(p.x+R(-380,380),20,WORLD.w-20),y:clamp(p.y+R(-380,380),20,WORLD.h-20)}}say(`🚶 A migration of ${count} souls begins in ${c.name}.`,true)}
const updateGod116=update;update=function(dt){for(const a of agents)if(a.godImmortal&&a.alive){a.age=Math.min(a.age,40);a.hp=Math.max(a.hp,100);a.hunger=Math.min(a.hunger,70)}updateGod116(dt)};
function refreshGodClanButtons(){let el=document.getElementById('godAgentClans');if(!el)return;el.innerHTML=clans.map(c=>`<button data-godclan="${c.id}" style="border:2px solid ${c.id===godAgentClan?'#111':'transparent'};background:${c.color};color:#fff">${c.em} ${c.name}</button>`).join('');el.querySelectorAll('[data-godclan]').forEach(b=>b.onclick=()=>{godAgentClan=+b.dataset.godclan;refreshGodClanButtons()})}
function installGodAgents(){let cards=document.getElementById('cards');if(!cards||document.getElementById('godAgentsBox'))return;let box=document.createElement('div');box.id='godAgentsBox';box.className='card';box.innerHTML=`<b>👥 Agents & Population</b><div class="mini">Choose a clan, then interfere with actual people.</div><div id="godAgentClans" style="display:flex;gap:5px;overflow-x:auto;margin:7px 0"></div><div class="grid" style="grid-template-columns:repeat(3,1fr)"><button data-spawn="random">🎲 Random</button><button data-spawn="worker">🧺 Worker</button><button data-spawn="builder">🔨 Builder</button><button data-spawn="guard">🛡 Guard</button><button data-spawn="raider">🪓 Raider</button><button data-spawn="scout">🏹 Scout</button><button data-spawn="medic">➕ Medic</button><button data-spawn="heavy">🔨 Heavy</button><button data-spawn="leader">👑 Leader</button></div><div class="grid"><button data-batch="5">+5</button><button data-batch="10">+10</button><button data-batch="25">+25</button><button id="godTapSpawn">📍 Tap Map</button></div><div class="section">Selected agent</div><div class="grid"><button id="godKillAgent">☠️ Kill</button><button id="godPromote">👑 Crown</button><button id="godImmortal">✨ Immortal</button><button id="godConvert">🔄 Convert</button></div><div class="section">Mass interference</div><div class="grid"><button id="godMigration">🚶 Migration</button><button id="godWipeArmy">💀 Wipe Army</button></div>`;cards.prepend(box);refreshGodClanButtons();box.querySelectorAll('[data-spawn]').forEach(b=>b.onclick=()=>{godSpawnRole=b.dataset.spawn;godSpawnCount=1;godSpawnHome(godSpawnRole,1)});box.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>{godSpawnCount=+b.dataset.batch;godSpawnHome('random',godSpawnCount)});document.getElementById('godTapSpawn').onclick=()=>{godAgentTapMode={role:godSpawnRole,count:godSpawnCount};document.getElementById('modal').classList.remove('open');mode='godagentspawn';$('focus').textContent=`⚡ GOD SPAWN • tap map for ${godSpawnCount} ${godSpawnRole}`};document.getElementById('godKillAgent').onclick=godKillSelected;document.getElementById('godPromote').onclick=godPromoteSelected;document.getElementById('godImmortal').onclick=godImmortalSelected;document.getElementById('godConvert').onclick=godConvertSelected;document.getElementById('godMigration').onclick=godMigration;document.getElementById('godWipeArmy').onclick=godWipeArmy}
const oldMore116=document.getElementById('more').onclick;document.getElementById('more').onclick=function(e){if(oldMore116)oldMore116.call(this,e);setTimeout(installGodAgents,0)};
C.addEventListener('pointerup',e=>{if(mode!=='godagentspawn'||!godAgentTapMode)return;let r=C.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,x=(sx-W/2)/cam.z+cam.x,y=(sy-H/2)/cam.z+cam.y,c=godClan();godSpawnAt(c,godAgentTapMode.role,godAgentTapMode.count,x,y);say(`⚡ ${godAgentTapMode.count} ${godAgentTapMode.role} appear in ${c.name}.`,true);godAgentTapMode=null;mode='watch';$('focus').textContent='👁 WATCH • tap people/buildings • drag • pinch zoom'},true);
document.querySelector('.brand small').textContent="Dad's Crazy Simulation • LIVING WORLD v11.6";
