'use strict';

const C=document.getElementById('world'),ctx=C.getContext('2d',{alpha:false}),$=id=>document.getElementById(id);
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),last=performance.now(),paused=false,mode='watch',director=true,chaos=false,simSpeed=1,maxSpeed=false,autoSaveClock=0,buildClan=0,buildType='farm';
let worldSetup={clans:4,agents:18,mode:'sandbox',resourceLevel:2};let pendingResume=null;
const SAVE_KEY='wos-scarcity-v8-autosave';const LEGACY_KEYS=['wos-scarcity-v7-autosave','wos-scarcity-v6-autosave','wos-scarcity-v5-autosave','wos-living-world'];
const WORLD={w:2100,h:1300},CELL=55,COLS=Math.ceil(WORLD.w/CELL),ROWS=Math.ceil(WORLD.h/CELL);
const COLORS=['#1f8cff','#ff405c','#33c96b','#ffc23f','#9b63ff','#ff8b38','#22c8c4','#ef6fbe'];
const NAMES=['Thistle','Kraken','Eagle','Camel','Stag','Badger','Fox','Raven'],EM=['🌿','🦑','🦅','🐪','🦌','🦡','🦊','🐦‍⬛'];
const ROLES=['worker','builder','guard','raider','medic','scout'],ROLEICON={worker:'F',builder:'B',guard:'G',raider:'R',medic:'+',scout:'S',leader:'★',heavy:'H'};
const PERSONAL=['bold','cautious','greedy','vengeful','builder','chaotic'];
let clans=[],agents=[],buildings=[],resources=[],fx=[],battles=[],history=[],year=0,clock=0,selected=null,headlineTimer=0,terrainCanvas=null,regen={food:1,wood:1,stone:1},cam={x:WORLD.w/2,y:WORLD.h/2,z:.55,tx:WORLD.w/2,ty:WORLD.h/2,tz:.55},drag=null,touches=new Map(),pinch=0;
window.__wosGetClans=()=>clans;
window.__wosGetAgents=()=>agents;
window.__wosGetBuildings=()=>buildings;
const R=(a,b)=>a+Math.random()*(b-a),ri=(a,b)=>Math.floor(R(a,b+1)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),pick=a=>a[ri(0,a.length-1)];
function say(msg,big=false){history.unshift({y:year,msg});history.length=70;$('feed').innerHTML=history.slice(0,3).map(h=>`<b>Y${h.y}</b> ${h.msg}`).join('<br>');if(big){$('headline').textContent=msg;$('headline').classList.add('on');headlineTimer=3.2}}
function namePerson(){return pick(['Rab','Mags','Tam','Moira','Barry','Agnes','Gav','Soup','Pickle','Nugget','Cheddar','Frankie'])+' '+pick(['McNibble','Crunch','Batter','Crisp','Dip','Snack','Broon','McCrumb'])}
function cellIndex(x,y){return clamp(Math.floor(y/CELL),0,ROWS-1)*COLS+clamp(Math.floor(x/CELL),0,COLS-1)}
function spawnAgent(c,x,y,role){let a={id:('a'+Date.now().toString(36)+Math.random().toString(36).slice(2)),c,x,y,vx:0,vy:0,role:role||pick(ROLES),hp:100,age:0,hunger:R(20,55),morale:R(55,90),fame:0,name:namePerson(),goal:null,think:R(0,2),memory:{killer:null,home:c},alive:true};agents.push(a);return a}
function addBuilding(c,x,y,type='camp'){let hp=type==='castle'?420:type==='watchtower'?220:180;buildings.push({c,x,y,type,hp,maxHp:hp,level:1,age:0,work:0})}
function createClan(i,x,y){let c={id:i,name:NAMES[i],em:EM[i],color:COLORS[i],home:{x,y},food:110,wood:80,stone:55,morale:R(60,85),rage:R(5,25),wealth:R(20,60),trait:PERSONAL[i%PERSONAL.length],war:new Set(),allies:new Set(),relations:{},kills:0,deaths:0,territory:0,leader:null,hero:null,grudge:{},buildClock:R(5,12),dipClock:R(5,14)};clans.push(c);addBuilding(i,x,y,'castle');addBuilding(i,x+R(-70,70),y+R(-70,70),'farm');for(let n=0;n<worldSetup.agents;n++){let role;if(worldSetup.mode==='totalwar')role=Math.random()<.55?pick(['guard','raider']):pick(ROLES);else if(worldSetup.mode==='peaceful')role=Math.random()<.48?pick(['worker','builder']):pick(ROLES);spawnAgent(i,x+R(-95,95),y+R(-95,95),role)}c.leader=spawnAgent(i,x+R(-25,25),y+R(-25,25),'leader');c.leader.name='Chief '+c.leader.name;return c}
function buildTerrain(){
  terrainCanvas=document.createElement('canvas'); terrainCanvas.width=WORLD.w; terrainCanvas.height=WORLD.h; const g=terrainCanvas.getContext('2d');
  const sky=g.createLinearGradient(0,0,0,WORLD.h); sky.addColorStop(0,'#314e3c'); sky.addColorStop(.5,'#3d6045'); sky.addColorStop(1,'#2e4d39'); g.fillStyle=sky; g.fillRect(0,0,WORLD.w,WORLD.h);
  for(let i=0;i<46;i++){const x=R(-80,WORLD.w+80),y=R(-80,WORLD.h+80),rx=R(90,260),ry=R(55,170);g.save();g.translate(x,y);g.rotate(R(-.45,.45));g.fillStyle=i%4===0?'rgba(92,110,67,.22)':i%3===0?'rgba(55,83,59,.27)':'rgba(121,137,77,.12)';g.beginPath();g.ellipse(0,0,rx,ry,0,0,7);g.fill();g.restore()}
  for(let r=0;r<2;r++){let sy=R(180,WORLD.h-180);g.lineCap='round';g.lineJoin='round';g.strokeStyle='rgba(20,38,34,.42)';g.lineWidth=34;g.beginPath();g.moveTo(-40,sy);for(let x=0;x<=WORLD.w+100;x+=180)g.lineTo(x,sy+Math.sin(x*.004+r*2)*R(55,95)+Math.sin(x*.011)*22);g.stroke();g.strokeStyle='#315c69';g.lineWidth=22;g.stroke();g.strokeStyle='rgba(164,211,218,.28)';g.lineWidth=3;g.stroke()}
  g.setLineDash([16,14]);g.strokeStyle='rgba(187,167,116,.34)';g.lineWidth=9;for(let i=0;i<6;i++){let y=R(90,WORLD.h-90);g.beginPath();g.moveTo(R(-100,120),y);g.bezierCurveTo(WORLD.w*.35,R(0,WORLD.h),WORLD.w*.7,R(0,WORLD.h),WORLD.w+100,R(0,WORLD.h));g.stroke()}g.setLineDash([]);
  for(let i=0;i<250;i++){let x=R(15,WORLD.w-15),y=R(15,WORLD.h-15);if(Math.random()<.78){g.fillStyle='rgba(20,55,34,.7)';g.beginPath();g.arc(x,y,R(3,7),0,7);g.fill();g.fillStyle='rgba(59,103,55,.7)';g.beginPath();g.arc(x-2,y-2,R(2,5),0,7);g.fill()}else{g.fillStyle='rgba(120,125,117,.55)';g.beginPath();g.ellipse(x,y,R(3,8),R(2,5),R(0,3),0,7);g.fill()}}
  const v=g.createRadialGradient(WORLD.w/2,WORLD.h/2,250,WORLD.w/2,WORLD.h/2,1200);v.addColorStop(0,'rgba(255,255,255,.02)');v.addColorStop(1,'rgba(0,0,0,.22)');g.fillStyle=v;g.fillRect(0,0,WORLD.w,WORLD.h)
}
function newWorld(){clans=[];agents=[];buildings=[];resources=[];fx=[];battles=[];history=[];year=0;clock=0;regen={food:1,wood:1,stone:1};chaos=worldSetup.mode==='chaos';buildTerrain();
const n=clamp(worldSetup.clans,2,8),cx=WORLD.w/2,cy=WORLD.h/2,rx=690,ry=430;for(let i=0;i<n;i++){let a=-Math.PI/2+i*Math.PI*2/n;createClan(i,cx+Math.cos(a)*rx,cy+Math.sin(a)*ry)}
let resourceBase=[65,105,150,205,270][clamp(worldSetup.resourceLevel,0,4)];if(worldSetup.mode==='scarcity')resourceBase=Math.floor(resourceBase*.62);if(worldSetup.mode==='collapse')resourceBase=Math.floor(resourceBase*.32);if(worldSetup.mode==='peaceful')resourceBase=Math.floor(resourceBase*1.35);for(let i=0;i<resourceBase;i++)resources.push({x:R(50,WORLD.w-50),y:R(50,WORLD.h-50),kind:Math.random()<.7?'food':Math.random()<.5?'wood':'stone',n:R(8,28)});
if(worldSetup.mode==='totalwar'){for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)setWar(a,b,true,'the world begins at war')}else if(worldSetup.mode==='scarcity'||worldSetup.mode==='collapse'){for(const c of clans){c.food*=worldSetup.mode==='collapse'?.28:.55;c.wood*=worldSetup.mode==='collapse'?.45:.7;c.rage+=worldSetup.mode==='collapse'?38:18;c.morale-=worldSetup.mode==='collapse'?22:8}if(n>1)setWar(0,1,true,'a fight over dwindling supplies')}else if(worldSetup.mode==='peaceful'){for(const c of clans){c.food+=140;c.wood+=100;c.stone+=65;c.rage=R(0,8);c.morale=R(78,96)}}else if(worldSetup.mode==='chaos'){for(const c of clans){c.rage=R(45,80);c.morale=R(38,78)}for(let i=0;i<Math.max(1,Math.floor(n/2));i++){let a=ri(0,n-1),b=ri(0,n-1);if(a!==b)setWar(a,b,true,'chaos at the dawn of history')}}else if(n>1)setWar(0,1,true,'old border feud');fit();say(`${n} snack kingdoms wake up — ${worldSetup.mode==='sandbox'?'history begins':worldSetup.mode}.`,true)}
function fit(){cam.tx=WORLD.w/2;cam.ty=WORLD.h/2;cam.tz=clamp(Math.min(W/WORLD.w,H/WORLD.h)*.96,.42,1.15);cam.x=cam.tx;cam.y=cam.ty;cam.z=cam.tz}
function setWar(a,b,on,cause='grudge'){let A=clans[a],B=clans[b];if(!A||!B||a===b)return;if(on){if(!A.war.has(b)){A.war.add(b);B.war.add(a);A.allies.delete(b);B.allies.delete(a);A.grudge[b]=(A.grudge[b]||0)+15;B.grudge[a]=(B.grudge[a]||0)+15;say(`⚔️ ${A.name} and ${B.name} go to war — ${cause}.`,true)}}else{A.war.delete(b);B.war.delete(a)}}
function nearestEnemy(a,range=260){let Cc=clans[a.c],best=null,bd=range*range;for(const o of agents){if(!o.alive||o.c===a.c||!Cc.war.has(o.c))continue;let dx=o.x-a.x,dy=o.y-a.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=o}}return best}
function nearestResource(a,kind){let best=null,bd=320*320;for(const r of resources){if(kind&&r.kind!==kind)continue;let dx=r.x-a.x,dy=r.y-a.y,d=dx*dx+dy*dy;if(d<bd&&r.n>0){bd=d;best=r}}return best}
function nearestFriendlyBuilding(a,type){let best=null,bd=1e9;for(const b of buildings){if(b.c!==a.c||(type&&b.type!==type))continue;let d=(a.x-b.x)**2+(a.y-b.y)**2;if(d<bd){bd=d;best=b}}return best}
function chooseGoal(a){let c=clans[a.c];a.think=R(.6,1.6);if(a.hp<45&&a.role!=='raider'){let h=nearestFriendlyBuilding(a,'hospital');if(h)return a.goal={type:'heal',x:h.x,y:h.y}}
let e=nearestEnemy(a,a.role==='scout'?380:280);if(e&&(a.role==='guard'||a.role==='raider'||c.rage>55||a.memory.killer===e.c))return a.goal={type:'fight',target:e};
if(a.hunger>72){let r=nearestResource(a,'food');if(r)return a.goal={type:'gather',target:r}}
if(a.role==='raider'&&c.war.size){let ec=[...c.war][0],t=buildings.find(b=>b.c===ec&&b.type==='farm')||buildings.find(b=>b.c===ec);if(t)return a.goal={type:'raid',target:t}}
if(a.role==='builder'&&c.wood>16&&Math.random()<.55)return a.goal={type:'build',x:clamp(c.home.x+R(-260,260),40,WORLD.w-40),y:clamp(c.home.y+R(-260,260),40,WORLD.h-40)}
if(a.role==='scout')return a.goal={type:'move',x:clamp(a.x+R(-420,420),30,WORLD.w-30),y:clamp(a.y+R(-420,420),30,WORLD.h-30)}
let r=nearestResource(a);if(r)return a.goal={type:'gather',target:r};return a.goal={type:'move',x:clamp(a.x+R(-170,170),20,WORLD.w-20),y:clamp(a.y+R(-170,170),20,WORLD.h-20)}}
function steer(a,x,y,speed,dt){let dx=x-a.x,dy=y-a.y,l=Math.hypot(dx,dy)||1;a.vx+=dx/l*speed*dt;a.vy+=dy/l*speed*dt}
function hit(att,def,dt,mult=1){if(Math.random()>dt*(att.role==='raider'?4.4:att.role==='guard'||att.role==='leader'?3.6:2.2))return;let dmg=R(5,13)*mult*(att.morale/80);def.hp-=dmg;fx.push({x:def.x,y:def.y,vx:R(-12,12),vy:R(-25,-8),life:.55,max:.55,text:'✦',color:clans[att.c].color});if(def.hp<=0&&def.alive){def.alive=false;let A=clans[att.c],D=clans[def.c];A.kills++;D.deaths++;A.grudge[def.c]=(A.grudge[def.c]||0)+1;D.grudge[att.c]=(D.grudge[att.c]||0)+5;att.fame+=2;att.morale=clamp(att.morale+8,0,100);if(def.role==='leader'){say(`☠️ ${D.name}'s leader ${def.name} falls to ${att.name}!`,true);spawnLeader(D)}else if(att.fame>12&&Math.random()<.2)say(`⭐ ${att.name} of ${A.name} is becoming a legend.`)}}
function spawnLeader(c){let a=spawnAgent(c.id,c.home.x+R(-30,30),c.home.y+R(-30,30),'leader');a.name='Chief '+namePerson();a.fame=4;c.leader=a;c.morale=clamp(c.morale-18,0,100)}
