/* v11.5 settlement planning, road walking, sieges */
let siegeFx=[],v115Clock=0;
function v115NearestOwn(b,types,max=9999){let best=null,bd=max;for(const o of buildings){if(o===b||o.hp<=0||o.c!==b.c||types&&!types.includes(o.type))continue;let d=dist(b,o);if(d<bd){bd=d;best=o}}return best}
function v115Placement(c,type,x,y){const own=buildings.filter(b=>b.hp>0&&b.c===c),castle=own.find(b=>b.type==='castle'),home=castle||{x,y};let ang=R(0,Math.PI*2),r=R(45,120);
 if(type==='farm'){r=R(150,245);ang=R(0,Math.PI*2)}
 else if(type==='hospital'){r=R(35,90)}
 else if(type==='barracks'){r=R(105,175)}
 else if(type==='watchtower'){r=R(185,270)}
 else if(type==='camp'){let n=own.length?pick(own):home;r=R(35,85);home=n}
 let px=clamp(home.x+Math.cos(ang)*r,35,WORLD.w-35),py=clamp(home.y+Math.sin(ang)*r,35,WORLD.h-35);
 for(let tries=0;tries<12;tries++){let crowd=buildings.some(b=>b.hp>0&&Math.hypot(b.x-px,b.y-py)<34);if(!crowd)break;ang+=.7;r+=12;px=clamp(home.x+Math.cos(ang)*r,35,WORLD.w-35);py=clamp(home.y+Math.sin(ang)*r,35,WORLD.h-35)}return{x:px,y:py}}
const addBuildingV115=addBuilding;addBuilding=function(c,x,y,type='camp'){if(mode!=='build'&&type!=='castle'){let p=v115Placement(c,type,x,y);x=p.x;y=p.y}return addBuildingV115(c,x,y,type)};
function v115RoadTarget(a){let own=buildings.filter(b=>b.hp>0&&b.c===a.c);if(own.length<2)return null;let near=own.sort((p,q)=>dist(a,p)-dist(a,q))[0];if(!near||dist(a,near)>95)return null;let next=v115NearestOwn(near,null,240);return next&&dist(a,next)>28?next:null}
const steerV115=steer;steer=function(a,x,y,speed,dt){if(a&&a.alive&&a.role!=='raider'&&Math.random()<.22){let road=v115RoadTarget(a);if(road){let goalD=Math.hypot(x-a.x,y-a.y),roadD=Math.hypot(road.x-a.x,road.y-a.y);if(roadD<goalD*.7){x=road.x;y=road.y;speed*=1.16}}}return steerV115(a,x,y,speed,dt)};
function v115Sieges(dt){for(const c of clans){if(!c.war.size)continue;for(const enemyId of c.war){let target=buildings.find(b=>b.hp>0&&b.c===enemyId&&b.type==='castle');if(!target)continue;let attackers=agents.filter(a=>a.alive&&a.c===c.id&&['leader','guard','raider','heavy'].includes(a.role)&&dist(a,target)<115),defenders=agents.filter(a=>a.alive&&a.c===enemyId&&dist(a,target)<125);if(attackers.length>=4){target.siege=(target.siege||0)+dt*attackers.length*.32;target.hp-=dt*Math.max(0,attackers.length-defenders.length*.55)*1.7;if(Math.random()<dt*.25)siegeFx.push({x:target.x+R(-35,35),y:target.y+R(-25,25),life:R(.6,1.3)});if(target.siege>18&&Math.random()<dt*.08)say(`🏰 ${c.name} is besieging ${clans[enemyId].name}'s capital.`);if(target.hp<=18||target.siege>75){let old=target.c;target.c=c.id;target.hp=target.maxHp*.42;target.siege=0;clans[c.id].home={x:target.x,y:target.y};for(const b of buildings)if(b.c===old&&dist(b,target)<155&&Math.random()<.72)b.c=c.id;for(const a of agents)if(a.alive&&a.c===old&&dist(a,target)<170){a.morale=clamp(a.morale-30,0,100);a.goal={type:'move',x:clans[old].home.x+R(-80,80),y:clans[old].home.y+R(-80,80)}}say(`🚩 ${c.name} captures the capital of ${clans[old].name}!`,true)}}}}for(const f of siegeFx)f.life-=dt;siegeFx=siegeFx.filter(f=>f.life>0)}
const updateV115=update;update=function(dt){updateV115(dt);v115Sieges(dt)};
const drawV115=draw;draw=function(){drawV115();if(povAgent)return;ctx.save();ctx.translate(W/2,H/2);ctx.scale(cam.z,cam.z);ctx.translate(-cam.x,-cam.y);for(const b of buildings){if(!b.siege)continue;ctx.strokeStyle='#ff9b52';ctx.lineWidth=4/cam.z;ctx.setLineDash([9/cam.z,7/cam.z]);ctx.beginPath();ctx.arc(b.x,b.y,58,0,7);ctx.stroke();ctx.setLineDash([])}for(const f of siegeFx){ctx.globalAlpha=clamp(f.life,0,1);ctx.fillStyle='#ffb347';ctx.beginPath();ctx.arc(f.x,f.y,8+8*(1-f.life),0,7);ctx.fill();ctx.fillStyle='#3b312c';ctx.beginPath();ctx.arc(f.x+R(-2,2),f.y-8,5,0,7);ctx.fill()}ctx.restore()};
document.querySelector('.brand small').textContent="Dad's Crazy Simulation • LIVING WORLD v11.5";
