/* v11 Living World */
let settlements=[],worldChronicle=[],armyOrders=[],tradeRoutes=[],weaponFx=[],livingClock=0,lastEraAnnounced=0;
const V11_ERA_NAMES=['Tribal Age','Age of Kingdoms','Fortified Age','Imperial Age','Age of Fracture'];
function v11Era(){return Math.min(4,Math.floor(year/450))}
function v11EraName(){return V11_ERA_NAMES[v11Era()]}
const spawnAgentV11=spawnAgent;
spawnAgent=function(c,x,y,role){const a=spawnAgentV11(c,x,y,role),clan=clans[c];if(clan){clan.dynastyName=clan.dynastyName||pick(['McCrumb','Crisp','Broon','Snack','Batter','Nibble']);a.dynasty=clan.dynastyName;const adults=agents.filter(o=>o!==a&&o.alive&&o.c===c&&o.age>28);if(adults.length>1){a.parent1=pick(adults).id;a.parent2=pick(adults.filter(o=>o.id!==a.parent1)).id}a.generation=1+Math.max(0,...adults.slice(-8).map(o=>o.generation||0));a.weapon=role==='scout'?'bow':role==='raider'?'axe':role==='heavy'?'maul':role==='guard'||role==='leader'?'spear':'tool';a.weaponSkill=R(.65,1.15)}return a};
const sayV11=say;say=function(msg,big=false){sayV11(msg,big);if(/war|falls|captures|famine|peace|leader|victory|siege|alliance|pact|starv|burn/i.test(msg)){worldChronicle.unshift({y:year,era:v11EraName(),msg});worldChronicle.length=140}};
function rebuildSettlements(){settlements=[];for(const c of clans){const own=buildings.filter(b=>b.hp>0&&b.c===c.id),anchors=own.filter(b=>b.type==='castle'||b.type==='camp');for(let i=0;i<anchors.length;i++){const a=anchors[i],near=own.filter(b=>Math.hypot(b.x-a.x,b.y-a.y)<230),pop=agents.filter(x=>x.alive&&x.c===c.id&&Math.hypot(x.x-a.x,x.y-a.y)<260).length;if(near.length<2&&pop<7)continue;const tier=pop>55||near.length>11?3:pop>28||near.length>7?2:1;settlements.push({c:c.id,x:a.x,y:a.y,pop,buildings:near.length,tier,name:(tier===3?'City of ':tier===2?'Town of ':'Village of ')+c.name+(i?' '+(i+1):'')})}}}
function settlementTick(dt){livingClock-=dt;if(livingClock>0)return;livingClock=5;rebuildSettlements();const era=v11Era();if(era!==lastEraAnnounced){lastEraAnnounced=era;say(`📜 ${v11EraName()} begins. The world has changed.`,true)}for(const c of clans){const own=settlements.filter(s=>s.c===c.id),live=agents.filter(a=>a.alive&&a.c===c.id);c.capital=own.sort((a,b)=>(b.tier*100+b.pop)-(a.tier*100+a.pop))[0]||null;c.militaryPower=live.reduce((n,a)=>n+(a.role==='leader'?3:a.role==='heavy'?2.4:a.role==='guard'?1.8:a.role==='raider'?1.6:a.role==='scout'?1.2:.25),0);c.foodSecurity=c.food/Math.max(1,live.length);c.era=era;if(c.leader&&c.leader.alive)c.rulerDynasty=c.leader.dynasty||c.dynastyName}tradeRoutes=[];for(const c of clans)for(const aid of c.allies){if(c.id>=aid)continue;const o=clans[aid];if(!o)continue;let give=c.foodSecurity>(o.foodSecurity||0)?c:o,recv=give===c?o:c;if(give.food>45){let amount=Math.min(3,give.food*.015);give.food-=amount;recv.food+=amount;give.wealth+=amount*.18;tradeRoutes.push({a:give.home,b:recv.home,c1:give.id,c2:recv.id})}}}
function militaryAgents(c){return agents.filter(a=>a.alive&&a.c===c.id&&['leader','guard','raider','heavy','scout'].includes(a.role))}
function armyTick(dt){for(const c of clans){c.armyClock=(c.armyClock||0)-dt;if(c.armyClock>0)continue;c.armyClock=R(5,9);const troops=militaryAgents(c);if(!c.war.size||troops.length<5)continue;const enemies=[...c.war].map(id=>clans[id]).filter(Boolean),targetClan=enemies.sort((a,b)=>(a.militaryPower||0)-(b.militaryPower||0))[0];if(!targetClan)continue;const objective=buildings.find(b=>b.hp>0&&b.c===targetClan.id&&b.type==='castle')||buildings.find(b=>b.hp>0&&b.c===targetClan.id);if(!objective)continue;const rally={x:c.home.x+(objective.x-c.home.x)*.18,y:c.home.y+(objective.y-c.home.y)*.18},order={c:c.id,target:targetClan.id,x:objective.x,y:objective.y,rally,year,phase:'march'};armyOrders=armyOrders.filter(o=>o.c!==c.id);armyOrders.push(order);troops.slice(0,Math.min(28,troops.length)).forEach((a,i)=>{const ang=i*.75,rr=12+Math.floor(i/6)*10;a.goal={type:'move',x:clamp(rally.x+Math.cos(ang)*rr,20,WORLD.w-20),y:clamp(rally.y+Math.sin(ang)*rr,20,WORLD.h-20)};a.armyTarget=objective;a.armyLaunch=clock+R(2,5)});if(Math.random()<.35)say(`⚔️ ${c.name} musters an army to march on ${targetClan.name}.`)}for(const a of agents){if(!a.alive||!a.armyTarget)continue;if(clock>(a.armyLaunch||0)&&(!a.goal||a.goal.type==='move')){if(a.armyTarget.hp>0)a.goal={type:'raid',target:a.armyTarget};else a.armyTarget=null}}}
function v11Shoot(from,to,kind,damage,speed){if(!from||!to||!to.alive)return;let dx=to.x-from.x,dy=to.y-from.y,l=Math.hypot(dx,dy)||1;projectiles.push({x:from.x,y:from.y,vx:dx/l*speed,vy:dy/l*speed,target:to,c:from.c,life:1.5,kind,damage});weaponFx.push({x:from.x,y:from.y,life:.18,kind:'flash'})}
function weaponTick(dt){for(const a of agents){if(!a.alive||!['guard','leader','raider','heavy'].includes(a.role))continue;a.v11Attack=(a.v11Attack||R(0,.8))-dt;if(a.v11Attack>0)continue;const e=nearestEnemy(a,a.role==='guard'||a.role==='leader'?115:34);if(!e)continue;const d=dist(a,e);if((a.role==='guard'||a.role==='leader')&&d>28){v11Shoot(a,e,'javelin',R(12,20)*(a.weaponSkill||1),245);a.v11Attack=R(1.8,2.7)}else if(d<30){const mult=a.role==='heavy'?1.8:a.role==='raider'?1.35:1.2;hit(a,e,dt*3.2,mult*(a.weaponSkill||1));weaponFx.push({x:(a.x+e.x)/2,y:(a.y+e.y)/2,life:.25,kind:'slash',c:a.c});a.v11Attack=R(.45,.85)}}for(const f of weaponFx)f.life-=dt;weaponFx=weaponFx.filter(f=>f.life>0)}
function successionTick(dt){for(const c of clans){if(c.leader&&c.leader.alive)continue;c.successionClock=(c.successionClock||0)-dt;if(c.successionClock>0)continue;c.successionClock=3;const candidates=agents.filter(a=>a.alive&&a.c===c.id).sort((a,b)=>(b.fame+(b.generation||0)*.5)-(a.fame+(a.generation||0)*.5));if(candidates[0]){const heir=candidates[0];heir.role='leader';heir.name=heir.name.startsWith('Chief ')?heir.name:'Chief '+heir.name;heir.fame+=5;c.leader=heir;c.rulerDynasty=heir.dynasty;say(`👑 ${heir.name} of House ${heir.dynasty||'Snack'} takes the ${c.name} throne.`,true)}}}
const updateV11=update;update=function(dt){updateV11(dt);settlementTick(dt);armyTick(dt);weaponTick(dt);successionTick(dt)};
function drawV11World(){if(povAgent)return;ctx.save();ctx.translate(W/2,H/2);ctx.scale(cam.z,cam.z);ctx.translate(-cam.x,-cam.y);for(const t of tradeRoutes){ctx.strokeStyle='rgba(245,218,123,.55)';ctx.lineWidth=2/cam.z;ctx.setLineDash([7/cam.z,7/cam.z]);ctx.beginPath();ctx.moveTo(t.a.x,t.a.y);ctx.lineTo(t.b.x,t.b.y);ctx.stroke()}ctx.setLineDash([]);for(const s of settlements){const c=clans[s.c];if(!c)continue;const r=s.tier===3?88:s.tier===2?62:42;ctx.strokeStyle=c.color;ctx.globalAlpha=.7;ctx.lineWidth=(s.tier+1)/cam.z;ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.stroke();if(s.tier>=2&&v11Era()>=2){ctx.strokeStyle='#c8b68a';ctx.globalAlpha=.7;ctx.lineWidth=5/cam.z;ctx.setLineDash([18/cam.z,5/cam.z]);ctx.beginPath();ctx.arc(s.x,s.y,r+8,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}ctx.globalAlpha=.95;ctx.fillStyle='#081019dd';ctx.fillRect(s.x-r*.65,s.y-r-22,r*1.3,15);ctx.fillStyle='#fff';ctx.font=`${10/cam.z}px system-ui`;ctx.textAlign='center';ctx.fillText(s.name,s.x,s.y-r-11)}for(const o of armyOrders){const c=clans[o.c];if(!c)continue;ctx.strokeStyle=c.color;ctx.globalAlpha=.75;ctx.lineWidth=4/cam.z;ctx.beginPath();ctx.moveTo(o.rally.x,o.rally.y);ctx.lineTo(o.x,o.y);ctx.stroke();ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(o.rally.x,o.rally.y,9/cam.z,0,7);ctx.fill()}for(const f of weaponFx){ctx.globalAlpha=clamp(f.life*5,0,1);ctx.strokeStyle=f.kind==='slash'?'#fff3c4':'#ffd76a';ctx.lineWidth=3/cam.z;ctx.beginPath();ctx.arc(f.x,f.y,12/cam.z,-1.2,.8);ctx.stroke()}ctx.restore()}
const drawV11=draw;draw=function(){drawV11();drawV11World()};
let historyBtn=document.createElement('button');historyBtn.textContent='📜 History';historyBtn.style.cssText='position:fixed;z-index:21;right:8px;top:calc(env(safe-area-inset-top) + 84px);padding:7px 9px;background:#f5f7fa;color:#111;border-radius:999px;font:900 9px system-ui';
let historySheet=document.createElement('div');historySheet.style.cssText='position:fixed;z-index:90;inset:0;display:none;background:#000a;align-items:flex-end';historySheet.innerHTML='<div style="width:100%;max-height:72%;overflow:auto;background:#f5f7fa;color:#101721;border-radius:22px 22px 0 0;padding:15px 13px calc(env(safe-area-inset-bottom) + 18px)"><button id="v11HistClose" style="float:right">Done</button><h2 style="margin:0">📜 World History</h2><div id="v11Era" style="font:900 11px system-ui;color:#66727d;margin:5px 0 12px"></div><div id="v11Hist"></div></div>';document.body.appendChild(historyBtn);document.body.appendChild(historySheet);
historyBtn.onclick=()=>{document.getElementById('v11Era').textContent=`Y${year} · ${v11EraName()} · ${settlements.length} settlements`;document.getElementById('v11Hist').innerHTML=(worldChronicle.length?worldChronicle:history).slice(0,50).map(h=>`<div style="padding:8px 0;border-bottom:1px solid #d8dee5;font:700 10px/1.35 system-ui"><b>Y${h.y}</b> ${h.msg}</div>`).join('');historySheet.style.display='flex'};
document.getElementById('v11HistClose').onclick=()=>historySheet.style.display='none';
document.querySelector('.brand small').textContent="Dad's Crazy Simulation • THE LIVING WORLD v11";
