/* v12 FRACTURE: refugees, rebellions, successor kingdoms, vassals and civil wars */
let fractureClock=3,refugeeFx=[],fractureNames=['Ember','Crownless','Moss','Iron','Ash','Salt','Thorn','Dusk','Hearth','Wolf','Black Crumb','Free Snack'],fractureEm=['🔥','👑','🌱','⚙️','🌑','🧂','🌵','🌘','🏠','🐺','⬛','🍪'];
function livingCount(c){return agents.filter(a=>a.alive&&a.c===c.id).length}
function militaryCount(c){return agents.filter(a=>a.alive&&a.c===c.id&&['leader','guard','raider','heavy','scout'].includes(a.role)).length}
function clanCastles(c){return buildings.filter(b=>b.hp>0&&b.c===c.id&&b.type==='castle')}
function safePointFor(c,x,y){let choices=settlements.filter(s=>s.c!==c.id&&!c.war.has(s.c));if(c.allies.size){let allied=choices.filter(s=>c.allies.has(s.c));if(allied.length)choices=allied}if(choices.length){choices.sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y));return choices[0]}let ang=R(0,Math.PI*2),r=R(220,420);return{x:clamp(x+Math.cos(ang)*r,35,WORLD.w-35),y:clamp(y+Math.sin(ang)*r,35,WORLD.h-35),c:null}}
function refugeeTick(){for(const c of clans){let live=agents.filter(a=>a.alive&&a.c===c.id&&!['guard','raider','heavy','leader'].includes(a.role));if(!live.length)continue;let stress=(c.war.size?22:0)+(c.food<Math.max(10,livingCount(c)*.25)?32:0)+(c.morale<38?26:0)+(c.deaths>c.kills+12?16:0);if(stress<35||Math.random()>.22)continue;let n=Math.min(4,Math.max(1,Math.floor(live.length*.08)));for(const a of live.sort(()=>Math.random()-.5).slice(0,n)){let safe=safePointFor(c,a.x,a.y);a.refugee=true;a.goal={type:'move',x:safe.x+R(-45,45),y:safe.y+R(-45,45)};a.morale=clamp(a.morale+6,0,100);refugeeFx.push({x:a.x,y:a.y,tx:safe.x,ty:safe.y,life:7,c:c.id});if(safe.c!=null&&Math.random()<.32){a.asylumClan=safe.c}}if(Math.random()<.35)say(`🚶 Families flee ${c.name} as refugees.`)}}
function refugeeArrivalTick(){for(const a of agents){if(!a.alive||!a.refugee)continue;if(a.goal&&a.goal.type==='move'&&Math.hypot(a.x-a.goal.x,a.y-a.goal.y)<38){if(a.asylumClan!=null&&clans[a.asylumClan]&&!clans[a.asylumClan].war.has(a.c)){let old=clans[a.c],dest=clans[a.asylumClan];a.c=dest.id;a.memory.home=dest.id;a.refugee=false;a.asylumClan=null;a.morale=R(62,88);if(Math.random()<.18)say(`🏠 Refugees from ${old.name} settle in ${dest.name}.`)}else{a.refugee=false;if(Math.random()<.16&&buildings.filter(b=>b.hp>0&&b.c===a.c&&Math.hypot(b.x-a.x,b.y-a.y)<150).length===0)addBuilding(a.c,a.x,a.y,'camp')}}}}
function newFractureClan(parent,center,reason){if(clans.length>=14)return null;let id=clans.length,base=fractureNames[(id-8)%fractureNames.length]||('Free '+id),suffix=Math.random()<.55?' League':Math.random()<.5?' Kingdom':' Republic',name=base+suffix,color=`hsl(${Math.floor((id*137.5+R(-18,18))%360)} 72% 54%)`,c={id,name,em:fractureEm[(id-8)%fractureEm.length]||'⚑',color,home:{x:center.x,y:center.y},food:Math.max(35,parent.food*.18),wood:Math.max(28,parent.wood*.16),stone:Math.max(16,parent.stone*.14),morale:R(62,88),rage:R(45,72),wealth:Math.max(12,parent.wealth*.15),trait:pick(PERSONAL),war:new Set(),allies:new Set(),relations:{},kills:0,deaths:0,territory:0,leader:null,hero:null,grudge:{},buildClock:R(4,9),dipClock:R(5,12),parentClan:parent.id,breakawayYear:year,breakawayReason:reason,dynastyName:pick(['Freefolk','Crisp','Broon','Ash','Thorn','McCrumb'])};clans.push(c);
 let local=agents.filter(a=>a.alive&&a.c===parent.id&&Math.hypot(a.x-center.x,a.y-center.y)<220);if(local.length<4)local=agents.filter(a=>a.alive&&a.c===parent.id).sort((a,b)=>Math.hypot(a.x-center.x,a.y-center.y)-Math.hypot(b.x-center.x,b.y-center.y)).slice(0,Math.min(8,livingCount(parent)));for(const a of local.slice(0,Math.max(4,Math.floor(local.length*.72)))){a.c=id;a.memory.home=id;a.morale=R(65,95);a.refugee=false}
 let localBuildings=buildings.filter(b=>b.hp>0&&b.c===parent.id&&b.type!=='castle'&&Math.hypot(b.x-center.x,b.y-center.y)<205);for(const b of localBuildings)b.c=id;addBuilding(id,center.x,center.y,'castle');let candidate=agents.filter(a=>a.alive&&a.c===id).sort((a,b)=>b.fame-a.fame)[0]||spawnAgent(id,center.x+R(-25,25),center.y+R(-25,25),'leader');candidate.role='leader';candidate.name=candidate.name.startsWith('Chief ')?candidate.name:'Chief '+candidate.name;candidate.fame+=8;c.leader=candidate;c.rulerDynasty=candidate.dynasty||c.dynastyName;parent.food*=.84;parent.wood*=.88;parent.stone*=.9;parent.morale=clamp(parent.morale-16,0,100);setWar(parent.id,id,true,reason||'a breakaway revolt');say(`🗺️ ${c.name} breaks away from ${parent.name}!`,true);return c}
function possibleBreakaway(c){if(clans.length>=14||livingCount(c)<14)return false;c.fractureCooldown=(c.fractureCooldown||0)-1;if(c.fractureCooldown>0)return false;let stress=(c.morale<34?30:0)+(c.food<12?20:0)+(c.war.size>=2?18:0)+(c.deaths>c.kills+18?20:0)+(c.vassalOf!=null?16:0);if(stress<42||Math.random()>.12)return false;let sites=settlements.filter(s=>s.c===c.id&&(!c.capital||Math.hypot(s.x-c.capital.x,s.y-c.capital.y)>170));let center=sites.length?pick(sites):{x:clamp(c.home.x+R(-300,300),60,WORLD.w-60),y:clamp(c.home.y+R(-260,260),60,WORLD.h-60)};newFractureClan(c,center,c.vassalOf!=null?'a revolt against foreign rule':'a civil war over hunger and authority');c.fractureCooldown=16;return true}
function vassalizeTick(c){if(c.vassalOf!=null){let lord=clans[c.vassalOf];if(!lord){c.vassalOf=null;return}let tribute=Math.min(c.food*.03,2.4);c.food-=tribute;lord.food+=tribute;lord.wealth+=Math.min(1.2,c.wealth*.012);c.overlordName=lord.name;setWar(c.id,lord.id,false);if(c.morale<28&&c.rage>58&&Math.random()<.12){c.vassalOf=null;c.rage=88;c.morale=54;setWar(c.id,lord.id,true,'a vassal rebellion');say(`🔥 ${c.name} renounces ${lord.name} and rises in revolt!`,true);return}for(const enemy of lord.war){if(enemy!==c.id&&clans[enemy]&&Math.random()<.18)setWar(c.id,enemy,true,'obligation to its overlord')}}else if(clanCastles(c).length===0&&livingCount(c)>2){let nearby=buildings.filter(b=>b.hp>0&&b.type==='castle'&&b.c!==c.id).sort((a,b)=>Math.hypot(a.x-c.home.x,a.y-c.home.y)-Math.hypot(b.x-c.home.x,b.y-c.home.y))[0];if(nearby&&Math.hypot(nearby.x-c.home.x,nearby.y-c.home.y)<330){let lord=clans[nearby.c];if(lord&&militaryCount(lord)>militaryCount(c)*1.25){c.vassalOf=lord.id;c.morale=clamp(c.morale-9,0,100);c.rage=clamp(c.rage+18,0,100);setWar(c.id,lord.id,false);say(`🛡️ ${c.name} becomes a vassal of ${lord.name}.`,true)}}}}
function fracturePolitics(){for(const c of clans.slice()){if(!c)continue;vassalizeTick(c);possibleBreakaway(c)}}
function fractureTick(dt){fractureClock-=dt;if(fractureClock>0)return;fractureClock=6;refugeeTick();refugeeArrivalTick();fracturePolitics();for(const f of refugeeFx)f.life-=6;refugeeFx=refugeeFx.filter(f=>f.life>0)}
const updateV12=update;update=function(dt){updateV12(dt);fractureTick(dt);refugeeArrivalTick()};
const drawV12=draw;draw=function(){drawV12();if(povAgent)return;ctx.save();ctx.translate(W/2,H/2);ctx.scale(cam.z,cam.z);ctx.translate(-cam.x,-cam.y);for(const f of refugeeFx){let c=clans[f.c];ctx.strokeStyle=(c&&c.color)||'#fff';ctx.globalAlpha=clamp(f.life/7,0,.5);ctx.lineWidth=1.5/cam.z;ctx.setLineDash([5/cam.z,7/cam.z]);ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(f.tx,f.ty);ctx.stroke()}ctx.setLineDash([]);for(const c of clans){if(c.vassalOf==null)continue;let lord=clans[c.vassalOf];if(!lord)continue;ctx.globalAlpha=.45;ctx.strokeStyle=lord.color;ctx.lineWidth=3/cam.z;ctx.setLineDash([12/cam.z,6/cam.z]);ctx.beginPath();ctx.moveTo(c.home.x,c.home.y);ctx.lineTo(lord.home.x,lord.home.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.font=`900 ${9/cam.z}px system-ui`;ctx.textAlign='center';ctx.fillText(`vassal of ${lord.name}`,c.home.x,c.home.y+28)}ctx.restore()};
const renderCardsV12=renderCards;renderCards=function(){renderCardsV12();if(!$('modal').classList.contains('open'))return;let cards=$('cards');if(!cards)return;for(const c of clans){if(c.vassalOf==null&&c.parentClan==null)continue;let tag=document.createElement('div');tag.className='card';let lord=c.vassalOf!=null?clans[c.vassalOf]:null,parent=c.parentClan!=null?clans[c.parentClan]:null;tag.innerHTML=`<b>${c.em} ${c.name}</b><div class="mini">${lord?`🛡 Vassal of ${lord.name}`:''}${lord&&parent?' • ':''}${parent?`🗺 Breakaway from ${parent.name} in Y${c.breakawayYear||year}`:''}</div>`;cards.appendChild(tag)}if(typeof installGodAgents==='function')installGodAgents()};
document.querySelector('.brand small').textContent="Dad's Crazy Simulation • FRACTURE v12";
