const pointers=new Map();let pinchState=null;
function clampCamera(){let halfW=W/(2*cam.z),halfH=H/(2*cam.z);if(halfW>=WORLD.w/2)cam.x=WORLD.w/2;else cam.x=clamp(cam.x,halfW,WORLD.w-halfW);if(halfH>=WORLD.h/2)cam.y=WORLD.h/2;else cam.y=clamp(cam.y,halfH,WORLD.h-halfH);cam.tx=cam.x;cam.ty=cam.y}
C.addEventListener('pointerdown',e=>{C.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false});director=false;$('director').classList.remove('on');if(pointers.size===2){let a=[...pointers.values()],cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2;pinchState={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z:cam.z,anchor:worldPoint(cx,cy),cx,cy}}});
C.addEventListener('pointermove',e=>{let p=pointers.get(e.pointerId);if(!p)return;let ox=p.x,oy=p.y;p.x=e.clientX;p.y=e.clientY;if(Math.hypot(p.x-p.sx,p.y-p.sy)>4)p.moved=true;if(pointers.size>=2){let a=[...pointers.values()].slice(0,2),cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(!pinchState||pinchState.dist<5)pinchState={dist,z:cam.z,anchor:worldPoint(cx,cy),cx,cy};let nz=clamp(pinchState.z*(dist/pinchState.dist),.42,2.7);cam.z=nz;cam.tz=nz;cam.x=pinchState.anchor.x-(cx-W/2)/nz;cam.y=pinchState.anchor.y-(cy-H/2)/nz;clampCamera();return}let dx=p.x-ox,dy=p.y-oy;if(Math.hypot(dx,dy)>0){cam.x-=dx/cam.z;cam.y-=dy/cam.z;clampCamera()}});
function endPointer(e){let p=pointers.get(e.pointerId);if(pointers.size===1&&p&&!p.moved)godTap(e.clientX,e.clientY);pointers.delete(e.pointerId);if(pointers.size<2)pinchState=null}
C.addEventListener('pointerup',endPointer);C.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(pointers.size<2)pinchState=null});
function setSpeed(v,silent=false){maxSpeed=v==='max';simSpeed=maxSpeed?1:Number(v);document.querySelectorAll('#speedPanel button').forEach(b=>b.classList.toggle('on',b.dataset.speed===String(v)));$('speedRead').textContent=maxSpeed?'MAX':simSpeed+'×';$('speedBtn').textContent='⏩ '+(maxSpeed?'MAX':simSpeed+'×');if(!silent)say(maxSpeed?'🚀 MAX speed — phone-limited simulation.':'⏩ Simulation speed '+simSpeed+'×.',true)}document.querySelectorAll('#speedPanel button').forEach(b=>b.onclick=()=>{setSpeed(b.dataset.speed);$('speedPanel').classList.remove('open')});$('speedBtn').onclick=()=>{$('speedPanel').classList.toggle('open')};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶ Play':'⏸ Pause'};
$('director').onclick=()=>{director=!director;$('director').classList.toggle('on',director);if(director)say('🎥 Director is hunting for stories.')};
$('bless').onclick=()=>{$('modal').classList.remove('open');mode='bless';$('focus').textContent='🍖 FOOD DROP • tap map'};
$('chaos').onclick=()=>{chaos=!chaos;$('chaos').classList.toggle('on',chaos);say(chaos?'🌀 Chaos mode armed. History is now drunk.':'Chaos calmed down.');renderCards()};
function renderBuildClans(){$('buildClan').innerHTML=clans.map(c=>`<button class="clanPick ${c.id===buildClan?'on':''}" data-clan="${c.id}" style="background:${c.color};color:#fff">${c.em} ${c.name}</button>`).join('');document.querySelectorAll('.clanPick').forEach(b=>b.onclick=()=>{buildClan=Number(b.dataset.clan);renderBuildClans()})}function chooseBuild(t){buildType=t;mode=t==='demolish'?'demolish':'build';document.querySelectorAll('.buildType').forEach(b=>b.classList.toggle('on',b.dataset.build===t));$('buildModal').classList.remove('open');$('focus').textContent=t==='demolish'?'💥 DEMOLISH • tap a building':'🏗 '+t.toUpperCase()+' for '+(clans[buildClan]?.name||'clan')+' • tap map'}$('buildBtn').onclick=()=>{renderBuildClans();$('buildModal').classList.add('open');$('speedPanel').classList.remove('open')};document.querySelectorAll('.buildType').forEach(b=>b.onclick=()=>chooseBuild(b.dataset.build));$('buildDone').onclick=()=>$('buildModal').classList.remove('open');$('more').onclick=()=>{$('modal').classList.add('open');$('speedPanel').classList.remove('open');renderCards()};$('close').onclick=()=>$('modal').classList.remove('open');
$('meteor').onclick=()=>{$('modal').classList.remove('open');mode='meteor';$('focus').textContent='☄️ METEOR • tap target'};
$('lightning').onclick=()=>{$('modal').classList.remove('open');mode='lightning';$('focus').textContent='⚡ LIGHTNING • tap target'};$('quake').onclick=()=>{quake();renderCards()};$('storm').onclick=()=>{divineStorm();renderCards()};$('feast').onclick=()=>{feastWorld();renderCards()};$('forest').onclick=()=>{growWood();renderCards()};$('blessClan').onclick=()=>{blessWeakest();renderCards()};$('curseClan').onclick=()=>{curseLeader();renderCards()};$('cutFood').onclick=()=>{cutResource('food');renderCards()};$('cutWood').onclick=()=>{cutResource('wood');renderCards()};$('cutStone').onclick=()=>{cutResource('stone');renderCards()};$('burnFarms').onclick=()=>{burnFarms();renderCards()};$('famine').onclick=()=>{famineClan();renderCards()};$('eraseArea').onclick=()=>{$('modal').classList.remove('open');mode='erase';$('focus').textContent='🕳 ERASE AREA • tap map to create scarcity'};$('restoreNature').onclick=()=>{restoreNature();renderCards()};
$('rebellion').onclick=()=>{rebellion();renderCards()};$('forcedWar').onclick=()=>{let a=pick(clans),b=pick(clans.filter(x=>x!==a));setWar(a.id,b.id,true,'divine interference');renderCards()};
$('peace').onclick=()=>{for(const c of clans)c.war.clear();say('🤝 An extremely suspicious world peace begins.',true);renderCards()};
$('hero').onclick=()=>{makeHero();renderCards()};$('save').onclick=save;$('load').onclick=()=>{load();renderCards()};$('newWorld').onclick=()=>{$('modal').classList.remove('open');openStartMenu(true)};
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);C.width=W*DPR;C.height=H*DPR;C.style.width=W+'px';C.style.height=H+'px'}
addEventListener('resize',resize);
function runSimulation(realDt){if(paused||!$('startScreen').classList.contains('hidden'))return;if(maxSpeed){const start=performance.now(),budget=13;let loops=0;while(performance.now()-start<budget&&loops<120){update(.5);loops++}return}let remaining=realDt*simSpeed;const step=simSpeed<=8?.035:simSpeed<=20?.06:simSpeed<=100?.12:simSpeed<=500?.28:.5;let loops=0,maxLoops=simSpeed<=20?160:simSpeed<=100?140:simSpeed<=500?110:90;while(remaining>0&&loops<maxLoops){let d=Math.min(step,remaining);update(d);remaining-=d;loops++}}
function frame(now){let realDt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;runSimulation(realDt);autoSaveClock+=realDt;if(autoSaveClock>=2){autoSaveClock=0;persist(true)}draw();requestAnimationFrame(frame)}
addEventListener('pagehide',()=>persist(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persist(true)});
function savedRaw(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw){for(const k of LEGACY_KEYS){raw=localStorage.getItem(k);if(raw)break}}return raw}catch(e){return null}}function openStartMenu(fromGame=false){paused=fromGame?true:paused;pendingResume=savedRaw();$('continueWorld').disabled=!pendingResume;$('saveNote').textContent=pendingResume?'Saved world found — Continue returns exactly where you left it.':'No saved world yet — create a new one.';$('startScreen').classList.remove('hidden')}function closeStartMenu(){$('startScreen').classList.add('hidden');last=performance.now()}const resNames=['Very Low','Low','Normal','Rich','Abundant'];function syncSetupUI(){$('clanVal').textContent=$('clanRange').value;$('agentVal').textContent=$('agentRange').value;$('resourceVal').textContent=resNames[Number($('resourceRange').value)]}$('clanRange').oninput=syncSetupUI;$('agentRange').oninput=syncSetupUI;$('resourceRange').oninput=syncSetupUI;document.querySelectorAll('.modeBtn').forEach(b=>b.onclick=()=>{worldSetup.mode=b.dataset.mode;document.querySelectorAll('.modeBtn').forEach(x=>x.classList.toggle('on',x===b));if(worldSetup.mode==='scarcity')$('resourceRange').value=1;else if(worldSetup.mode==='collapse')$('resourceRange').value=0;else if(worldSetup.mode==='peaceful')$('resourceRange').value=4;else $('resourceRange').value=2;syncSetupUI()});$('continueWorld').onclick=()=>{if(!pendingResume)return;if(restore(pendingResume,true)){paused=false;closeStartMenu();say('📂 History resumes.',true);persist(true)}};$('startNew').onclick=()=>{worldSetup.clans=Number($('clanRange').value);worldSetup.agents=Number($('agentRange').value);worldSetup.resourceLevel=Number($('resourceRange').value);try{localStorage.removeItem(SAVE_KEY)}catch(e){}paused=false;newWorld();persist(true);closeStartMenu()};resize();syncSetupUI();openStartMenu(false);requestAnimationFrame(frame);
