function updateAgent(a,dt){if(!a.alive)return;a.age+=dt;a.hunger=clamp(a.hunger+dt*1.15,0,100);a.morale+=(clans[a.c].morale-a.morale)*dt*.03;if(a.age>R(170,260)||a.hunger>=100){a.alive=false;clans[a.c].deaths++;return}a.think-=dt;if(a.think<=0||!a.goal||a.goal.target&&!a.goal.target.alive&&a.goal.type==='fight')chooseGoal(a);let g=a.goal,c=clans[a.c];if(g){if(g.type==='fight'&&g.target?.alive){let d=dist(a,g.target);if(d<18)hit(a,g.target,dt);else steer(a,g.target.x,g.target.y,95,dt)}
else if(g.type==='raid'&&g.target){let d=dist(a,g.target);if(d<22){g.target.hp-=dt*12;c.food+=dt*1.8;if(g.target.hp<=0){say(`🔥 ${c.name} burns a ${g.target.type} belonging to ${clans[g.target.c].name}.`);g.target.hp=0;g.target=null;a.goal=null}}else steer(a,g.target.x,g.target.y,85,dt)}
else if(g.type==='gather'&&g.target){let d=dist(a,g.target);if(d<18){let take=Math.min(g.target.n,dt*5);g.target.n-=take;if(g.target.kind==='food'){c.food+=take;a.hunger=Math.max(0,a.hunger-take*5)}else c[g.target.kind]+=take;if(g.target.n<=0)a.goal=null}else steer(a,g.target.x,g.target.y,55,dt)}
else if(g.type==='build'){let d=Math.hypot(a.x-g.x,a.y-g.y);if(d<18){if(c.wood>14){let t=c.food<35?'farm':c.war.size&&Math.random()<.55?'barracks':agents.filter(x=>x.c===c.id&&x.hp<60).length>3?'hospital':Math.random()<.4?'watchtower':'farm';addBuilding(a.c,g.x,g.y,t);c.wood-=14;c.stone=Math.max(0,c.stone-5);say(`🏗️ ${c.name} builds a ${t} on the frontier.`);a.goal=null}}else steer(a,g.x,g.y,50,dt)}
else if(g.type==='heal'){let d=Math.hypot(a.x-g.x,a.y-g.y);if(d<25){a.hp=clamp(a.hp+dt*20,0,100);if(a.hp>88)a.goal=null}else steer(a,g.x,g.y,55,dt)}
else if(g.type==='move'){let d=Math.hypot(a.x-g.x,a.y-g.y);if(d<20)a.goal=null;else steer(a,g.x,g.y,45,dt)}}
let max=a.role==='raider'?68:a.role==='scout'?72:a.role==='guard'?58:48,l=Math.hypot(a.vx,a.vy);if(l>max){a.vx=a.vx/l*max;a.vy=a.vy/l*max}a.vx*=.91;a.vy*=.91;a.x=clamp(a.x+a.vx*dt,8,WORLD.w-8);a.y=clamp(a.y+a.vy*dt,8,WORLD.h-8)}
function clanTick(c,dt){let live=agents.filter(a=>a.alive&&a.c===c.id),own=buildings.filter(b=>b.hp>0&&b.c===c.id),farms=own.filter(b=>b.type==='farm').length,barr=own.filter(b=>b.type==='barracks').length,hosp=own.filter(b=>b.type==='hospital').length,towers=own.filter(b=>b.type==='watchtower').length;c.food+=farms*dt*.48;c.wood+=own.filter(b=>b.type==='camp').length*dt*.08;c.food-=live.length*dt*.045;c.morale=clamp(c.morale+dt*(c.food>20?.25:-1.1)+hosp*dt*.015,0,100);c.rage=clamp(c.rage+dt*(c.trait==='vengeful'?.15:-.02)-towers*dt*.005,0,100);if(c.food<12){c.rage=clamp(c.rage+dt*.9,0,100);c.morale=clamp(c.morale-dt*.45,0,100);if(c.rage>58&&Math.random()<dt*.018){let target=clans.filter(o=>o.id!==c.id&&!c.war.has(o.id)).sort((a,b)=>b.food-a.food)[0];if(target&&target.food>c.food+15)setWar(c.id,target.id,true,'desperate food raid')}}for(const b of own){b.age+=dt;b.work+=dt;if(b.work>35&&b.level<3&&c.wood>22&&c.stone>12){b.level++;b.work=0;b.maxHp=(b.maxHp||b.hp)+70;b.hp=b.maxHp;c.wood-=22;c.stone-=12;say(`🏗️ ${c.name} upgrades its ${b.type} to level ${b.level}.`)}}
if(c.food>35&&live.length<95&&Math.random()<dt*(.15+.04*farms)){let role=Math.random()<Math.min(.55,.15+barr*.05)?'guard':pick(ROLES);spawnAgent(c.id,c.home.x+R(-75,75),c.home.y+R(-75,75),role);c.food-=7}
c.dipClock-=dt;if(c.dipClock<=0){c.dipClock=R(7,15);let others=clans.filter(o=>o.id!==c.id),o=pick(others),g=c.grudge[o.id]||0;if(c.war.has(o.id)){if(c.morale<35||Math.random()<.12){setWar(c.id,o.id,false);say(`🤝 ${c.name} and ${o.name} sign an uneasy peace.`)}}else if(g>22||c.rage>72||c.trait==='chaotic'&&Math.random()<.25){setWar(c.id,o.id,true,g>22?'an old blood debt':'pure bad judgement')}else if(g<5&&Math.random()<.14){c.allies.add(o.id);o.allies.add(c.id);say(`🤝 ${c.name} and ${o.name} form a snack pact.`)}}}
function updateTerritory(){for(const c of clans)c.territory=0;for(let gy=0;gy<ROWS;gy++)for(let gx=0;gx<COLS;gx++){let x=gx*CELL+CELL/2,y=gy*CELL+CELL/2,best=null,score=-1e9;for(const c of clans){let s=-Math.hypot(x-c.home.x,y-c.home.y);for(const b of buildings)if(b.c===c.id&&b.hp>0)s=Math.max(s,180-Math.hypot(x-b.x,y-b.y));for(const a of agents)if(a.alive&&a.c===c.id)s=Math.max(s,75-Math.hypot(x-a.x,y-a.y));if(s>score){score=s;best=c}}if(best&&score>-260)best.territory++}}
function battleDetect(){for(let i=0;i<agents.length;i++){let a=agents[i];if(!a.alive)continue;let e=nearestEnemy(a,70);if(e&&Math.random()<.025){battles.push({x:(a.x+e.x)/2,y:(a.y+e.y)/2,a:a.c,b:e.c,life:5,max:5});if(director&&Math.random()<.35){cam.tx=(a.x+e.x)/2;cam.ty=(a.y+e.y)/2;cam.tz=Math.max(cam.z,1.15);say(`🎥 Border clash: ${clans[a.c].name} vs ${clans[e.c].name}!`)}}}battles=battles.filter(b=>(b.life-=.3)>0)}
function randomEvent(){let c=pick(clans);if(Math.random()<.45){c.food+=35;say(`🍟 A legendary snack cache is found by ${c.name}.`)}else if(Math.random()<.5){c.morale=clamp(c.morale+18,0,100);say(`🎉 ${c.name} invents a national holiday for crisps.`)}else{let o=pick(clans.filter(x=>x!==c));c.grudge[o.id]=(c.grudge[o.id]||0)+12;say(`😡 ${c.name} blames ${o.name} for a suspiciously missing sausage roll.`)}}
function update(dt){clock+=dt;year=Math.floor(clock/5);for(const c of clans)clanTick(c,dt);for(const a of agents)updateAgent(a,dt);agents=agents.filter(a=>a.alive);buildings=buildings.filter(b=>b.hp>0);resources=resources.filter(r=>r.n>0);if(resources.length<160&&Math.random()<dt*2){let wf=.72*regen.food,ww=.14*regen.wood,ws=.14*regen.stone,sum=wf+ww+ws;if(sum>0){let q=Math.random()*sum,kind=q<wf?'food':q<wf+ww?'wood':'stone';resources.push({x:R(30,WORLD.w-30),y:R(30,WORLD.h-30),kind,n:R(8,25)})}}
for(const f of fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.life-=dt}fx=fx.filter(f=>f.life>0);if(Math.random()<dt*.18)battleDetect();if(Math.random()<dt*(chaos?.035:.007))randomEvent();if(Math.floor(clock*2)%12===0)updateTerritory();headlineTimer-=dt;if(headlineTimer<=0)$('headline').classList.remove('on');
if(director){let hot=battles.sort((a,b)=>b.life-a.life)[0];if(hot&&Math.random()<dt*.9){cam.tx=hot.x;cam.ty=hot.y;cam.tz=1.25}else if(Math.random()<dt*.04){let hero=agents.filter(a=>a.alive).sort((a,b)=>b.fame-a.fame)[0];if(hero&&hero.fame>4){cam.tx=hero.x;cam.ty=hero.y;cam.tz=1.05}}}
cam.x+=(cam.tx-cam.x)*dt*2.4;cam.y+=(cam.ty-cam.y)*dt*2.4;cam.z+=(cam.tz-cam.z)*dt*2.4}
function drawTerrain(){if(terrainCanvas)ctx.drawImage(terrainCanvas,0,0);else{ctx.fillStyle='#355744';ctx.fillRect(0,0,WORLD.w,WORLD.h)}}
function drawTerritory(){for(const c of clans){ctx.save();ctx.globalAlpha=.08;ctx.fillStyle=c.color;for(const b of buildings){if(b.c!==c.id||b.hp<=0)continue;ctx.beginPath();ctx.arc(b.x,b.y,b.type==='castle'?180:110,0,7);ctx.fill()}ctx.restore()}}
function drawRoads(){ctx.save();ctx.lineCap='round';for(const c of clans){const home=buildings.find(b=>b.c===c.id&&b.type==='castle');if(!home)continue;for(const b of buildings){if(b.c!==c.id||b===home)continue;ctx.strokeStyle='rgba(54,43,30,.28)';ctx.lineWidth=8/cam.z;ctx.beginPath();ctx.moveTo(home.x,home.y);ctx.quadraticCurveTo((home.x+b.x)/2+Math.sin(b.x*.02)*30,(home.y+b.y)/2+Math.cos(b.y*.02)*30,b.x,b.y);ctx.stroke();ctx.strokeStyle='rgba(206,178,120,.32)';ctx.lineWidth=3/cam.z;ctx.stroke()}}ctx.restore()}
